branches:
  only:
    - master
skip_tags: false
environment:
  release_name: "oxipay-woocommerce_v%appveyor_build_version%.zip"
build_script:
  - ps: Invoke-Expression "7z a $env:release_name"
artifacts:
  - path: $(release_name)
    name: $(appveyor_build_version)
    type: zip
deploy:
  release: v$(appveyor_build_version)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  provider: GitHub
  auth_token:
    secure: 56NAOqpMQYkuaKqIWixuwuHbYK+1VYaGXQITooXcBLAL1b5xYAAENylYsXh029zy
  artifact: /.*\.zip/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: false
    appveyor_repo_tag_name: 'release'
notifications:
  - provider: Email
    to:
      - devadmin@oxipay.com.au

